記事関連を作成・テスト済み
nagatani-aoi/sanda-zero-carbon-app-backend pull request #76
Opened 2022-09-30 13:31 UTC by SSatoShun

記事関連を作成しました。
作成・変更したプログラム
- コントローラ
    - ArticleManagementRestController
    管理者用記事コントローラ
    - ArticleRestController
    記事コントローラ
- サービス
    - ArticleService
    記事サービス
    - ArticleManagementService
    管理者用記事サービス
- データのやりとり
    - ArticleDto
    - ArticleForm
- バリデーション
    - ArticleValidationException
- リポジトリ
    - ArticleRepository

2022-10-06 09:18 UTC, nagatani-aoi requested changes
- ざっとテストしてみた感じ挙動は問題なかったです．
- しかし，一点気になった点としては，String型はかなりの文字長をサポートしているはずですが，SQLによって文字長が制限されて，discriptionが入りきらない場合がありました．
  - SQLによる制約の解除か，入力できる最大文字長の調査をお願いしてもいいですか？

2022-10-06 09:18 UTC, nagatani-aoi commented on sanda-zero-carbon-app-backend/src/main/java/jp/kobespiral/sandazerocarbonappbackend/application/controller/ArticleManagementRestController.java
> +    @DeleteMapping("/sanda-admin/article")
Javadog 付け忘れ

2022-10-07 00:38 UTC, YoshifumiKamae approved these changes
確認しました。

2022-10-07 01:23 UTC, nagatani-aoi approved these changes

2022-10-07 01:23 UTC, merged